Controllers/AcoountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models.Users;

namespace WebApplication1.Controllers
{
    public class AcoountController : Controller
    {
        UserManager<AppUser> userManager;
        SignInManager<AppUser> signInManager;

        public AcoountController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Login()
        {
            var result=await signInManager.PasswordSignInAsync("TestUser", "Test", false, false);
            if (result.Succeeded) {
            ViewBag.msg = "Zalogowano pomyślnie";
            }
            else
            {
                ViewBag.msg = "Błędy: "+result;
            }
            return View();
        }
        public async Task< IActionResult> Register()
        {
            var user = await userManager.FindByNameAsync("TestUser");
            if (user != null) { 
                ViewBag.msg = "Użytkownik o podanej nazwie istnieje";
            }
            else
            {
                user = new AppUser()
                {
                    UserName = "TestUser",
                    Email = "testuser@ukw.edu.pl",
                    FirstName = "Jan",
                    LastName = "Kowalski"
                };
                var result =await userManager.CreateAsync(user,"Test");
                ViewBag.msg = result.ToString(); ;

            }
                return View();
        }
    }
}

Views/Shared/Components/Menu/_Menu.cshtml
@model IEnumerable<Category>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <ul class="navbar-nav">
            @foreach (var category in Model)
            {
                <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("FilmsList","Films", new {categoryName=@category.Name})">@category.Name</a>
                </li>
            }
            <li>
                <a class="btn btn-danger" href="@Url.Action("AllFilms", "Films")">Wszystkie</a>
            </li>
            <li>
                <a class="btn btn-success" href="@Url.Action("AddFilm", "Films")">Dodaj nowy film</a>
            </li>

            @if (User.Identity.IsAuthenticated)
            {
                <li>
                    <a class="btn btn-success" href="@Url.Action("Logout", "Acoount")">Wyloguj</a>
                </li>
            }
            else
            {
                
                <li>
                    <a class="btn btn-success" href="@Url.Action("Register", "Acoount")">Register</a>
                </li>
                <li>
                    <a class="btn btn-success" href="@Url.Action("Login", "Acoount")">Login</a>
                </li>
                
            }
            



        </ul>
    </div>
</nav>