Models/Film.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Film
    {
        public int FilmId { get; set; }
        [Required]
        public string Title { get; set; }
        public string Director { get; set; }
        [StringLength(600,ErrorMessage ="Przekroczono limit znaków")]
        public string Desc { get; set; }
        public decimal? Price { get; set; }
        public string Poster { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DAL;
using WebApplication1.Infrastructure;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        FilmsContext db;
        public CartController(FilmsContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            var cart = CartManager.GetItems(HttpContext.Session);
            ViewBag.Total = CartManager.GetCartValue(HttpContext.Session);
            return View(cart);
        }
        public IActionResult AddToCart(int filmId/*, string returnUrl = null*/)
        {
            CartManager.AddToCart(HttpContext.Session, filmId, db);
            //if (!string.IsNullOrEmpty(returnUrl))
            //{
            //    return Redirect(returnUrl);
            //}
            return RedirectToAction("Index");
        }
        public IActionResult RemoveFromCart(int id)
        {
            var model = new RemoveViewModel()
            {
                itemId = id,
                itemQuantity = CartManager.RemoveFromCart(HttpContext.Session, id),
                cartValue = CartManager.GetCartValue(HttpContext.Session)
            };
            return Json(model);
        }
        
    }
}

Controllers/FilmsController.cs
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class FilmsController : Controller
    {
        FilmsContext db;
        IWebHostEnvironment webHost;

        public FilmsController(FilmsContext db, IWebHostEnvironment webHost)
        {
            this.db = db;
            this.webHost = webHost;
        }

        public IActionResult AllFilms()
        {
            return View(db.Films.ToList());
        }

        public IActionResult FilmsList(string categoryName)
        {
            var category = db.Categories.Include("Films").Where(c => c.Name.ToUpper() == categoryName.ToUpper()).Single();
            var films = category.Films.ToList();
            KategoriaViewModel model = new KategoriaViewModel();
            model.Kategoria = category;
            model.FilmyKategorii = films;
            model.FilmyNajnowsze = db.Films.OrderByDescending(f => f.FilmId).Take(3);
            return View(films);
        }

        public IActionResult Details(int filmId)
        {
            var film = db.Films.Find(filmId);
            if(film != null)
            {
                db.Categories.Find(film.CategoryId);
            }
            return View(film);
        }
        [HttpGet]
        public IActionResult AddFilm()
        {
            AddViewModel model = new AddViewModel();
            model.AllCategories = db.Categories.ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult AddFilm(AddViewModel model)
        {
            var posterFolderPath = Path.Combine(webHost.WebRootPath, "posters");
            var uniquePosterName = model.Poster.FileName + "_" + Guid.NewGuid()+Path.GetExtension(model.Poster.FileName);
            var filePath = Path.Combine(posterFolderPath, uniquePosterName);
            model.Poster.CopyTo(new FileStream(filePath, FileMode.Create));
            model.NewFilm.Poster = uniquePosterName;
            db.Films.Add(model.NewFilm);
            db.SaveChanges();
            return RedirectToAction("AddFilm");
        }
    }
}

ViewComponents/SideMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.DAL;

namespace WebApplication1.ViewComponents
{
    public class SideMenuViewComponent :ViewComponent
    {
        FilmsContext db;
        public SideMenuViewComponent(FilmsContext db)
        {
            this.db = db;
        }
        
        public async Task<IViewComponentResult> InvokeAsync(string categoryName)
        {
            var category = db.Categories.Include("Films").Where(c => c.Name.ToUpper() == categoryName.ToUpper()).FirstOrDefault();
            var films = category.Films.OrderBy(f => f.Title).ToList();
            return await Task.FromResult(View("_SideMenu", films));
        }
    }
}

Views/Films/AddFilm.cshtml
@model AddViewModel
@{
	ViewData["Title"] = "Dodawanie filmu";
}

@using (Html.BeginForm("AddFilm", "Films", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Title, "Tytuł:") </b>
			@Html.TextBoxFor(m => m.NewFilm.Title, new { @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Director, "Reżyser:") </b>
			@Html.TextBoxFor(m => m.NewFilm.Director, new { @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Price, "Cena:") </b>
			@Html.TextBoxFor(m => m.NewFilm.Price, new { Type = "number", @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Desc, "Opis:") </b>
			@Html.TextAreaFor(m => m.NewFilm.Desc, new { @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.Poster, "Plakat:") </b>
			@Html.TextBoxFor(m => m.Poster, new { Type = "file", @class = "form-control-file", @required = true })
		</div>
		<div class="form-check">
			@foreach (var category in Model.AllCategories)
			{
				@Html.RadioButtonFor(m => m.NewFilm.CategoryId, category.CategoryId, new { @class = "from-check-input" })
				@category.Name
				<br />
			}
		</div>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Dodaj</button>
	</div>
}

Views/Films/AllFilms.cshtml
@model IEnumerable<Film>
<div class="container">
    <div class="row g-4">
        @foreach (var film in Model)
        {
            <div class="col-md-4 col-sm-6 d-flex justify-content-center">
                <a href="@Url.Action("Details","Films", new { filmId = film.FilmId })"><img src="~/posters/@film.Poster" alt="Film @film.Poster" class="movie-poster" height="300px"></a>
            </div>
        }
    </div>
</div>

Views/Films/Details.cshtml
@model Film

<table>
    <tr>
        <td>
            <h2>@Model.Category.Name</h2>
            @(await Component.InvokeAsync("SideMenu",new {categoryName=Model.Category.Name}))
        </td>
        <td>
            <img src="~/posters/@Model.Poster" height="250px" alt="Grafika @Model.Poster"/>
        </td>
        <td>
            <ul>
                <li><b>Tytuł: </b> @Model.Title</li>
                <li><b>Reżyser:</b> @Model.Director</li>
                <li><b>Cena:</b> @Model.Price</li>
                <li><b>Opis:</b> @Model.Desc</li>
                <li><a href="@Url.Action("AddToCart","Cart",new {filmId=Model.FilmId})">🛒</a></li>
            </ul>
            
        </td>
        <td>

        </td>
    </tr>
</table>

Views/Films/FilmsList.cshtml
@model IEnumerable<Film>
@{
    ViewData["Title"] = "Kategoria " + Model.FirstOrDefault().Category.Name;
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Tytuł filmu</th>
            <th>Reżyser</th>
            <th>Opis</th>
            <th>Cena</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var film in Model)
        {
            <tr>
            <td>@film.Title</td>
            <td>@film.Director</td>
            <td>@film.Desc</td>
            <td>@film.Price zł</td>
            <td><a href="@Url.Action("Details", "Films", new { filmId = film.FilmId })">🔍</a></td>
            </tr>
        }
    </tbody>
</table>